// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNfBVHDS-xx2ugPGJg_mhsGL8mSjGDDY',
    appId: '1:728159855584:web:e5c3d1e50ba59afcb2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    authDomain: 'flutter-chatapp-7a814.firebaseapp.com',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
    measurementId: 'G-SWZKED2LRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQj0sjezA5XSt8IgLbcvyl6v02nr6EJZY',
    appId: '1:728159855584:android:332a2fda602fbda1b2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxEWpUMJGID-FX1NRJYnpDYXVqmvBCT0',
    appId: '1:728159855584:ios:4f9b2ad848d735c0b2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvNfBVHDS-xx2ugPGJg_mhsGL8mSjGDDY',
    appId: '1:728159855584:web:3293ccaab1f8de0cb2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    authDomain: 'flutter-chatapp-7a814.firebaseapp.com',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
    measurementId: 'G-16WRNVG4ML',
  );

}