// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0nVxMyja32QEo19rG3H_Pz1PLi_8u2gE',
    appId: '1:521232452622:web:6e3b66bb294dceb3a9c05f',
    messagingSenderId: '521232452622',
    projectId: 'shopping-app-89638',
    authDomain: 'shopping-app-89638.firebaseapp.com',
    storageBucket: 'shopping-app-89638.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt1F8hPAV3ww2-bsBDjane35HE5gpVFn4',
    appId: '1:521232452622:android:100df1924e7d669ba9c05f',
    messagingSenderId: '521232452622',
    projectId: 'shopping-app-89638',
    storageBucket: 'shopping-app-89638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxEWpUMJGID-FX1NRJYnpDYXVqmvBCT0',
    appId: '1:728159855584:ios:0baee9a7db5a7b88b2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxEWpUMJGID-FX1NRJYnpDYXVqmvBCT0',
    appId: '1:728159855584:ios:0baee9a7db5a7b88b2c185',
    messagingSenderId: '728159855584',
    projectId: 'flutter-chatapp-7a814',
    storageBucket: 'flutter-chatapp-7a814.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0nVxMyja32QEo19rG3H_Pz1PLi_8u2gE',
    appId: '1:521232452622:web:5394114b53a1324ca9c05f',
    messagingSenderId: '521232452622',
    projectId: 'shopping-app-89638',
    authDomain: 'shopping-app-89638.firebaseapp.com',
    storageBucket: 'shopping-app-89638.firebasestorage.app',
  );

}